version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


  workspace:
    build:
      context: .
      dockerfile: Dockerfile.workspace
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      # Mounts the project folder to '/workspace'. While this file is in .devcontainer,
      # mounts are relative to the first file in the list, which is a level up.
      - ..:/workspace:cached

    # [Optional] Required for ptrace-based debuggers like C++, Go, and Rust
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    ports:
      - "1234:1234"

#     volumes: 
#       - db:/var/lib/postgresql/data
# volumes:
#   db:
#     driver: local
